preferences:
  webhook_overlay_search:
    description: Configuration option for your search results
    inputs:
      - name: max_search_results
        label: Maximum number of search results
        type: text
        required: False

  use_cached_job:
    description: Do you want to be able to re-use previously run jobs ?
    inputs:
      - name: use_cached_job_checkbox
        label: Do you want to be able to re-use  equivalent jobs ?
        type: boolean
        checked: false
        value: false
        help: If you select yes, you will be able to select for each tool and workflow run if you would like to use this feature.

  localization:
    description: Localization
    inputs:
      - name: locale
        label: Prefered language
        type: select
        required: False
        options:
          - [Navigator default, auto]
          - [中文, zh]
          - [English, en]
          - [Español, es]
          - [Français, fr]
          - [日本語, ja]

  distributed_arc_compute:
    description: The URL to your ARC remote HPC compute resource.
    inputs:
      - name: remote_arc_resources
        label: "Add your remote resource url (example: https://arctestcluster-slurm-el9-arc7-ce1.cern-test.uiocloud.no)"
        type: text
        required: False

  distributed_compute:
    description: Use distributed compute resources
    inputs:
      - name: remote_resources
        label: Remote resources id
        type: select
        required: False
        options:
          - ["Select the remote resources", None]
          - ["default - Galaxy will decide where to put your job", None]
          - ["EGI Italy - INFN-CLOUD-BARI", egi-bari]
          - ["EGI Slovakia - IISAS-FedCloud", egi-iisas]

  ega_account:
    description: Your EGA (European Genome Archive) account
    inputs:
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  dropbox:
    description: Your Dropbox account
    inputs:
      - name: access_token
        label: Dropbox access token
        type: password
        required: False

  # Used in file_sources_conf.yml
  nextcloud:
    description: Your Personal Nextcloud / ownCloud account
    inputs:
      - name: url
        label: Server Domain (e.g. https://myowncloud.org)
        type: text
        required: False
      - name: root
        label: Server Path (should end with /remote.php/webdav, e.g. /a/sub/path/remote.php/webdav)
        type: text
        required: False
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  # Require to attach pulsar endpoint to the Pulsar Network
  byoc_pulsar:
    description: >
        Bring your own Pulsar endpoint to Galaxy. You can add here your Pulsar credentials and specifications.
        After 24 hours Galaxy's job scheduling systems will take your Pulsar into account and schedule appropriate jobs to your compute resources.
        This is an experimental feature. Contact us if you want to learn more about it.
    inputs:
      - name: username
        label: RabbitMQ custom username (e.g. mypulsarendpoint).
        type: text
        required: True
      - name: password
        label: RabbitMQ custom alphanumerical password, at least 10 characters long (e.g. MyPulS4rP4ssw0rd).
        type: password
        required: True
      - name: max_accepted_cores
        label: Maximum number of CPU cores available.
        type: number
        required: True
      - name: max_accepted_mem
        label: Maximum number of RAM available (in GB).
        type: number
        required: True
      - name: min_accepted_gpus
        label: Minimum number of GPU available (set this to zero if you don't want to share GPUs).
        type: number
        required: True
      - name: max_accepted_gpus
        label: Maximum number of GPU available (set this to zero if you don't want to share GPUs).
        type: number
        required: True

  omero_account:
    description: Your OMERO instance connection details
    inputs:
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  ena_webin_account:
    description: Your ENA Webin account details
    inputs:
      - name: webin_id
        label: ENA Webin ID
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  c3s_account:
    description: Your CDS API Key (Copernicus Climate Change Service API Key)
    inputs:
      - name: c3s_cds_apikey
        label: C3S CDS API Key
        type: password
        required: False

  cads_account:
    description: Your Copernicus ADS API Key (Copernicus Atmosphere Data Store API Key)
    inputs:
      - name: cads_apikey
        label: Copernicus ADS API Key
        type: password
        required: False

  gitlabfs:
    description: Your DataPLANT ARC Gitlab access details https://git.nfdi4plants.org
    inputs:
      - name: read_access_token
        label: API Read Access Token
        type: password
        required: True
